services:
  app:
    build: .
    command: sh -c "npm install && npx nodemon development.js"
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - 127.0.0.1:4800:3000
